version: 3

dotenv: ['.env']

env:
  LLVM_HOME: "/usr/lib/llvm-15"
  LD_LIBRARY_PATH: "/usr/lib/llvm-15/lib:$LD_LIBRARY_PATH"

tasks:
  build:
    cmds:
      - gradle -Pjdk19_home="${JAVA_HOME}" -Pllvm_home="${LLVM_HOME}" clean verify




