version: 3

dotenv: ['.env']

env:
  LLVM_HOME: "libs/clang_llvm"
  JTREG_HOME: "/usr/lib/jtreg"

vars:
  PROJECT_ROOT:
    sh: echo $PWD
  YARA_JAVA_ROOT: "samples/yara/yara-java"
  YARA_JAVA_SRC: "{{.YARA_JAVA_ROOT}}/src/main/java"
  YARA_JAVA_RESOURCES: "{{.YARA_JAVA_ROOT}}/src/main/resources"
  YARA_JAVA_HEADERS: "{{.YARA_JAVA_RESOURCES}}/headers"

tasks:
  setup:
    cmds:
      - mkdir -p libs/clang_llvm
      - true || wget -nc -O libs/clang_llvm.tar.xz --show-progress https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz
      - tar --strip-components=1 -xvf libs/clang_llvm.tar.xz -C libs/clang_llvm
  build:
    cmds:
      - gradle -Pjdk19_home="${JAVA_HOME}" -Pllvm_home="${LLVM_HOME}" clean verify
  test:
    cmds:
      - gradle -Pjdk19_home="${JAVA_HOME}" -Pllvm_home="${LLVM_HOME}" -Pjtreg_home="${JTREG_HOME}" jtreg
  yara-headers:
    cmds:
      - mkdir -p {{.YARA_JAVA_HEADERS}}
      - cp /usr/include/yara.h {{.YARA_JAVA_HEADERS}}
      - cp -r /usr/include/yara {{.YARA_JAVA_HEADERS}}
  yara-java:
    cmds:
      - task: yara-java-includes
      - sh -c "(
                build/jextract/bin/jextract
                -l yara
                --source
                --output {{.YARA_JAVA_SRC}}
                --target-package com.virustotal.yara
                {{.YARA_JAVA_HEADERS}}/yara.h
              )"
  yara-java-includes:
    cmds:
      - mkdir -p {{.YARA_JAVA_RESOURCES}}
      - sh -c "(
                build/jextract/bin/jextract
                --dump-includes {{.YARA_JAVA_RESOURCES}}/includes.txt
                {{.YARA_JAVA_HEADERS}}/yara.h
              )"
