// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$153 {

    static final FunctionDescriptor __fminf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fminf$MH = RuntimeHelper.downcallHandle(
        "__fminf",
        constants$153.__fminf$FUNC
    );
    static final FunctionDescriptor fmaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fmaf$MH = RuntimeHelper.downcallHandle(
        "fmaf",
        constants$153.fmaf$FUNC
    );
    static final FunctionDescriptor __fmaf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fmaf$MH = RuntimeHelper.downcallHandle(
        "__fmaf",
        constants$153.__fmaf$FUNC
    );
    static final FunctionDescriptor scalbf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle scalbf$MH = RuntimeHelper.downcallHandle(
        "scalbf",
        constants$153.scalbf$FUNC
    );
    static final FunctionDescriptor __scalbf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __scalbf$MH = RuntimeHelper.downcallHandle(
        "__scalbf",
        constants$153.__scalbf$FUNC
    );
    static final  OfInt signgam$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle signgam$VH = constants$153.signgam$LAYOUT.varHandle();
    static final MemorySegment signgam$SEGMENT = RuntimeHelper.lookupGlobalVariable("signgam", constants$153.signgam$LAYOUT);
}


