// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$155 {

    static final FunctionDescriptor yr_scanner_define_boolean_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_scanner_define_boolean_variable$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_define_boolean_variable",
        constants$155.yr_scanner_define_boolean_variable$FUNC
    );
    static final FunctionDescriptor yr_scanner_define_float_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle yr_scanner_define_float_variable$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_define_float_variable",
        constants$155.yr_scanner_define_float_variable$FUNC
    );
    static final FunctionDescriptor yr_scanner_define_string_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_define_string_variable$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_define_string_variable",
        constants$155.yr_scanner_define_string_variable$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_mem_blocks$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_mem_blocks$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_mem_blocks",
        constants$155.yr_scanner_scan_mem_blocks$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_mem$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_mem$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_mem",
        constants$155.yr_scanner_scan_mem$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_file$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_file",
        constants$155.yr_scanner_scan_file$FUNC
    );
}


