// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$149 {

    static final FunctionDescriptor __ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __ilogbf$MH = RuntimeHelper.downcallHandle(
        "__ilogbf",
        constants$149.__ilogbf$FUNC
    );
    static final FunctionDescriptor scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle scalblnf$MH = RuntimeHelper.downcallHandle(
        "scalblnf",
        constants$149.scalblnf$FUNC
    );
    static final FunctionDescriptor __scalblnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __scalblnf$MH = RuntimeHelper.downcallHandle(
        "__scalblnf",
        constants$149.__scalblnf$FUNC
    );
    static final FunctionDescriptor nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle nearbyintf$MH = RuntimeHelper.downcallHandle(
        "nearbyintf",
        constants$149.nearbyintf$FUNC
    );
    static final FunctionDescriptor __nearbyintf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __nearbyintf$MH = RuntimeHelper.downcallHandle(
        "__nearbyintf",
        constants$149.__nearbyintf$FUNC
    );
    static final FunctionDescriptor roundf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle roundf$MH = RuntimeHelper.downcallHandle(
        "roundf",
        constants$149.roundf$FUNC
    );
}


