// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$46 {

    static final FunctionDescriptor isdigit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isdigit$MH = RuntimeHelper.downcallHandle(
        "isdigit",
        constants$46.isdigit$FUNC
    );
    static final FunctionDescriptor islower$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle islower$MH = RuntimeHelper.downcallHandle(
        "islower",
        constants$46.islower$FUNC
    );
    static final FunctionDescriptor isgraph$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isgraph$MH = RuntimeHelper.downcallHandle(
        "isgraph",
        constants$46.isgraph$FUNC
    );
    static final FunctionDescriptor isprint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isprint$MH = RuntimeHelper.downcallHandle(
        "isprint",
        constants$46.isprint$FUNC
    );
    static final FunctionDescriptor ispunct$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle ispunct$MH = RuntimeHelper.downcallHandle(
        "ispunct",
        constants$46.ispunct$FUNC
    );
    static final FunctionDescriptor isspace$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isspace$MH = RuntimeHelper.downcallHandle(
        "isspace",
        constants$46.isspace$FUNC
    );
}


