// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$125 {

    static final FunctionDescriptor __ilogb$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __ilogb$MH = RuntimeHelper.downcallHandle(
        "__ilogb",
        constants$125.__ilogb$FUNC
    );
    static final FunctionDescriptor scalbln$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle scalbln$MH = RuntimeHelper.downcallHandle(
        "scalbln",
        constants$125.scalbln$FUNC
    );
    static final FunctionDescriptor __scalbln$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __scalbln$MH = RuntimeHelper.downcallHandle(
        "__scalbln",
        constants$125.__scalbln$FUNC
    );
    static final FunctionDescriptor nearbyint$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle nearbyint$MH = RuntimeHelper.downcallHandle(
        "nearbyint",
        constants$125.nearbyint$FUNC
    );
    static final FunctionDescriptor __nearbyint$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __nearbyint$MH = RuntimeHelper.downcallHandle(
        "__nearbyint",
        constants$125.__nearbyint$FUNC
    );
    static final FunctionDescriptor round$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle round$MH = RuntimeHelper.downcallHandle(
        "round",
        constants$125.round$FUNC
    );
}


