// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$54 {

    static final FunctionDescriptor yr_arena_write_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_write_data$MH = RuntimeHelper.downcallHandle(
        "yr_arena_write_data",
        constants$54.yr_arena_write_data$FUNC
    );
    static final FunctionDescriptor yr_arena_write_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_write_string$MH = RuntimeHelper.downcallHandle(
        "yr_arena_write_string",
        constants$54.yr_arena_write_string$FUNC
    );
    static final FunctionDescriptor yr_arena_write_uint32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_write_uint32$MH = RuntimeHelper.downcallHandle(
        "yr_arena_write_uint32",
        constants$54.yr_arena_write_uint32$FUNC
    );
    static final FunctionDescriptor yr_arena_load_stream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_load_stream$MH = RuntimeHelper.downcallHandle(
        "yr_arena_load_stream",
        constants$54.yr_arena_load_stream$FUNC
    );
    static final FunctionDescriptor yr_arena_save_stream$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_arena_save_stream$MH = RuntimeHelper.downcallHandle(
        "yr_arena_save_stream",
        constants$54.yr_arena_save_stream$FUNC
    );
    static final FunctionDescriptor ss_compare$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle ss_compare$MH = RuntimeHelper.downcallHandle(
        "ss_compare",
        constants$54.ss_compare$FUNC
    );
}


