// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$143 {

    static final FunctionDescriptor nanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nanf$MH = RuntimeHelper.downcallHandle(
        "nanf",
        constants$143.nanf$FUNC
    );
    static final FunctionDescriptor __nanf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __nanf$MH = RuntimeHelper.downcallHandle(
        "__nanf",
        constants$143.__nanf$FUNC
    );
    static final FunctionDescriptor isnanf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle isnanf$MH = RuntimeHelper.downcallHandle(
        "isnanf",
        constants$143.isnanf$FUNC
    );
    static final FunctionDescriptor j0f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle j0f$MH = RuntimeHelper.downcallHandle(
        "j0f",
        constants$143.j0f$FUNC
    );
    static final FunctionDescriptor __j0f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __j0f$MH = RuntimeHelper.downcallHandle(
        "__j0f",
        constants$143.__j0f$FUNC
    );
    static final FunctionDescriptor j1f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle j1f$MH = RuntimeHelper.downcallHandle(
        "j1f",
        constants$143.j1f$FUNC
    );
}


