// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$152 {

    static final FunctionDescriptor __llroundf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __llroundf$MH = RuntimeHelper.downcallHandle(
        "__llroundf",
        constants$152.__llroundf$FUNC
    );
    static final FunctionDescriptor fdimf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fdimf$MH = RuntimeHelper.downcallHandle(
        "fdimf",
        constants$152.fdimf$FUNC
    );
    static final FunctionDescriptor __fdimf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fdimf$MH = RuntimeHelper.downcallHandle(
        "__fdimf",
        constants$152.__fdimf$FUNC
    );
    static final FunctionDescriptor fmaxf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fmaxf$MH = RuntimeHelper.downcallHandle(
        "fmaxf",
        constants$152.fmaxf$FUNC
    );
    static final FunctionDescriptor __fmaxf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fmaxf$MH = RuntimeHelper.downcallHandle(
        "__fmaxf",
        constants$152.__fmaxf$FUNC
    );
    static final FunctionDescriptor fminf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle fminf$MH = RuntimeHelper.downcallHandle(
        "fminf",
        constants$152.fminf$FUNC
    );
}


