// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$156 {

    static final FunctionDescriptor yr_scanner_scan_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_fd$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_fd",
        constants$156.yr_scanner_scan_fd$FUNC
    );
    static final FunctionDescriptor yr_scanner_scan_proc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_scanner_scan_proc$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_scan_proc",
        constants$156.yr_scanner_scan_proc$FUNC
    );
    static final FunctionDescriptor yr_scanner_last_error_rule$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_last_error_rule$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_last_error_rule",
        constants$156.yr_scanner_last_error_rule$FUNC
    );
    static final FunctionDescriptor yr_scanner_last_error_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_last_error_string$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_last_error_string",
        constants$156.yr_scanner_last_error_string$FUNC
    );
    static final FunctionDescriptor yr_scanner_get_profiling_info$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_get_profiling_info$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_get_profiling_info",
        constants$156.yr_scanner_get_profiling_info$FUNC
    );
    static final FunctionDescriptor yr_scanner_reset_profiling_info$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_reset_profiling_info$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_reset_profiling_info",
        constants$156.yr_scanner_reset_profiling_info$FUNC
    );
}


