// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$104 {

    static final FunctionDescriptor yr_finalize$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle yr_finalize$MH = RuntimeHelper.downcallHandle(
        "yr_finalize",
        constants$104.yr_finalize$FUNC
    );
    static final FunctionDescriptor yr_set_configuration$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_set_configuration$MH = RuntimeHelper.downcallHandle(
        "yr_set_configuration",
        constants$104.yr_set_configuration$FUNC
    );
    static final FunctionDescriptor yr_get_configuration$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_get_configuration$MH = RuntimeHelper.downcallHandle(
        "yr_get_configuration",
        constants$104.yr_get_configuration$FUNC
    );
    static final FunctionDescriptor yr_calloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_calloc$MH = RuntimeHelper.downcallHandle(
        "yr_calloc",
        constants$104.yr_calloc$FUNC
    );
    static final FunctionDescriptor yr_malloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_malloc$MH = RuntimeHelper.downcallHandle(
        "yr_malloc",
        constants$104.yr_malloc$FUNC
    );
    static final FunctionDescriptor yr_realloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_realloc$MH = RuntimeHelper.downcallHandle(
        "yr_realloc",
        constants$104.yr_realloc$FUNC
    );
}


