// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$45 {

    static final FunctionDescriptor __ctype_b_loc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __ctype_b_loc$MH = RuntimeHelper.downcallHandle(
        "__ctype_b_loc",
        constants$45.__ctype_b_loc$FUNC
    );
    static final FunctionDescriptor __ctype_tolower_loc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __ctype_tolower_loc$MH = RuntimeHelper.downcallHandle(
        "__ctype_tolower_loc",
        constants$45.__ctype_tolower_loc$FUNC
    );
    static final FunctionDescriptor __ctype_toupper_loc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle __ctype_toupper_loc$MH = RuntimeHelper.downcallHandle(
        "__ctype_toupper_loc",
        constants$45.__ctype_toupper_loc$FUNC
    );
    static final FunctionDescriptor isalnum$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isalnum$MH = RuntimeHelper.downcallHandle(
        "isalnum",
        constants$45.isalnum$FUNC
    );
    static final FunctionDescriptor isalpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle isalpha$MH = RuntimeHelper.downcallHandle(
        "isalpha",
        constants$45.isalpha$FUNC
    );
    static final FunctionDescriptor iscntrl$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle iscntrl$MH = RuntimeHelper.downcallHandle(
        "iscntrl",
        constants$45.iscntrl$FUNC
    );
}


