// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$148 {

    static final FunctionDescriptor __nextafterf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __nextafterf$MH = RuntimeHelper.downcallHandle(
        "__nextafterf",
        constants$148.__nextafterf$FUNC
    );
    static final FunctionDescriptor remainderf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle remainderf$MH = RuntimeHelper.downcallHandle(
        "remainderf",
        constants$148.remainderf$FUNC
    );
    static final FunctionDescriptor __remainderf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __remainderf$MH = RuntimeHelper.downcallHandle(
        "__remainderf",
        constants$148.__remainderf$FUNC
    );
    static final FunctionDescriptor scalbnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle scalbnf$MH = RuntimeHelper.downcallHandle(
        "scalbnf",
        constants$148.scalbnf$FUNC
    );
    static final FunctionDescriptor __scalbnf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __scalbnf$MH = RuntimeHelper.downcallHandle(
        "__scalbnf",
        constants$148.__scalbnf$FUNC
    );
    static final FunctionDescriptor ilogbf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle ilogbf$MH = RuntimeHelper.downcallHandle(
        "ilogbf",
        constants$148.ilogbf$FUNC
    );
}


