// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$127 {

    static final FunctionDescriptor __lrint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __lrint$MH = RuntimeHelper.downcallHandle(
        "__lrint",
        constants$127.__lrint$FUNC
    );
    static final FunctionDescriptor llrint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle llrint$MH = RuntimeHelper.downcallHandle(
        "llrint",
        constants$127.llrint$FUNC
    );
    static final FunctionDescriptor __llrint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __llrint$MH = RuntimeHelper.downcallHandle(
        "__llrint",
        constants$127.__llrint$FUNC
    );
    static final FunctionDescriptor lround$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle lround$MH = RuntimeHelper.downcallHandle(
        "lround",
        constants$127.lround$FUNC
    );
    static final FunctionDescriptor __lround$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __lround$MH = RuntimeHelper.downcallHandle(
        "__lround",
        constants$127.__lround$FUNC
    );
    static final FunctionDescriptor llround$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle llround$MH = RuntimeHelper.downcallHandle(
        "llround",
        constants$127.llround$FUNC
    );
}


