// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$164 {

    static final FunctionDescriptor yr_object_get_root$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_get_root$MH = RuntimeHelper.downcallHandle(
        "yr_object_get_root",
        constants$164.yr_object_get_root$FUNC
    );
    static final FunctionDescriptor yr_object_print_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_object_print_data$MH = RuntimeHelper.downcallHandle(
        "yr_object_print_data",
        constants$164.yr_object_print_data$FUNC
    );
    static final FunctionDescriptor YR_EXT_INITIALIZE_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_EXT_INITIALIZE_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$164.YR_EXT_INITIALIZE_FUNC$FUNC
    );
    static final FunctionDescriptor YR_EXT_FINALIZE_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_EXT_FINALIZE_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$164.YR_EXT_FINALIZE_FUNC$FUNC
    );
}


