// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$95 {

    static final FunctionDescriptor yr_re_compile$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_compile$MH = RuntimeHelper.downcallHandle(
        "yr_re_compile",
        constants$95.yr_re_compile$FUNC
    );
    static final FunctionDescriptor yr_re_match$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_re_match$MH = RuntimeHelper.downcallHandle(
        "yr_re_match",
        constants$95.yr_re_match$FUNC
    );
    static final FunctionDescriptor YR_ATOMS_QUALITY_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_ATOMS_QUALITY_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$95.YR_ATOMS_QUALITY_FUNC$FUNC
    );
    static final FunctionDescriptor yr_atoms_extract_from_re$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("flags"),
            Constants$root.C_CHAR$LAYOUT.withName("xor_min"),
            Constants$root.C_CHAR$LAYOUT.withName("xor_max"),
            MemoryLayout.paddingLayout(16),
            Constants$root.C_POINTER$LAYOUT.withName("alphabet")
        ).withName("YR_MODIFIER"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_extract_from_re$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_extract_from_re",
        constants$95.yr_atoms_extract_from_re$FUNC
    );
    static final FunctionDescriptor yr_atoms_extract_from_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("flags"),
            Constants$root.C_CHAR$LAYOUT.withName("xor_min"),
            Constants$root.C_CHAR$LAYOUT.withName("xor_max"),
            MemoryLayout.paddingLayout(16),
            Constants$root.C_POINTER$LAYOUT.withName("alphabet")
        ).withName("YR_MODIFIER"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_atoms_extract_from_string$MH = RuntimeHelper.downcallHandle(
        "yr_atoms_extract_from_string",
        constants$95.yr_atoms_extract_from_string$FUNC
    );
}


