// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$151 {

    static final FunctionDescriptor __lrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __lrintf$MH = RuntimeHelper.downcallHandle(
        "__lrintf",
        constants$151.__lrintf$FUNC
    );
    static final FunctionDescriptor llrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle llrintf$MH = RuntimeHelper.downcallHandle(
        "llrintf",
        constants$151.llrintf$FUNC
    );
    static final FunctionDescriptor __llrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __llrintf$MH = RuntimeHelper.downcallHandle(
        "__llrintf",
        constants$151.__llrintf$FUNC
    );
    static final FunctionDescriptor lroundf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle lroundf$MH = RuntimeHelper.downcallHandle(
        "lroundf",
        constants$151.lroundf$FUNC
    );
    static final FunctionDescriptor __lroundf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __lroundf$MH = RuntimeHelper.downcallHandle(
        "__lroundf",
        constants$151.__lroundf$FUNC
    );
    static final FunctionDescriptor llroundf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle llroundf$MH = RuntimeHelper.downcallHandle(
        "llroundf",
        constants$151.llroundf$FUNC
    );
}


