// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$111 {

    static final FunctionDescriptor atanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle atanh$MH = RuntimeHelper.downcallHandle(
        "atanh",
        constants$111.atanh$FUNC
    );
    static final FunctionDescriptor __atanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __atanh$MH = RuntimeHelper.downcallHandle(
        "__atanh",
        constants$111.__atanh$FUNC
    );
    static final FunctionDescriptor exp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle exp$MH = RuntimeHelper.downcallHandle(
        "exp",
        constants$111.exp$FUNC
    );
    static final FunctionDescriptor __exp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __exp$MH = RuntimeHelper.downcallHandle(
        "__exp",
        constants$111.__exp$FUNC
    );
    static final FunctionDescriptor frexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle frexp$MH = RuntimeHelper.downcallHandle(
        "frexp",
        constants$111.frexp$FUNC
    );
    static final FunctionDescriptor __frexp$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __frexp$MH = RuntimeHelper.downcallHandle(
        "__frexp",
        constants$111.__frexp$FUNC
    );
}


