// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$57 {

    static final FunctionDescriptor YR_HASH_TABLE_FREE_VALUE_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_HASH_TABLE_FREE_VALUE_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$57.YR_HASH_TABLE_FREE_VALUE_FUNC$FUNC
    );
    static final FunctionDescriptor yr_hash$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_hash$MH = RuntimeHelper.downcallHandle(
        "yr_hash",
        constants$57.yr_hash$FUNC
    );
    static final FunctionDescriptor yr_hash_table_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_hash_table_create$MH = RuntimeHelper.downcallHandle(
        "yr_hash_table_create",
        constants$57.yr_hash_table_create$FUNC
    );
    static final FunctionDescriptor yr_hash_table_clean$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_hash_table_clean$MH = RuntimeHelper.downcallHandle(
        "yr_hash_table_clean",
        constants$57.yr_hash_table_clean$FUNC
    );
    static final FunctionDescriptor yr_hash_table_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_hash_table_destroy$MH = RuntimeHelper.downcallHandle(
        "yr_hash_table_destroy",
        constants$57.yr_hash_table_destroy$FUNC
    );
    static final FunctionDescriptor yr_hash_table_lookup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_hash_table_lookup$MH = RuntimeHelper.downcallHandle(
        "yr_hash_table_lookup",
        constants$57.yr_hash_table_lookup$FUNC
    );
}


