// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$106 {

    static final FunctionDescriptor __signbit$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __signbit$MH = RuntimeHelper.downcallHandle(
        "__signbit",
        constants$106.__signbit$FUNC
    );
    static final FunctionDescriptor __isinf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isinf$MH = RuntimeHelper.downcallHandle(
        "__isinf",
        constants$106.__isinf$FUNC
    );
    static final FunctionDescriptor __finite$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __finite$MH = RuntimeHelper.downcallHandle(
        "__finite",
        constants$106.__finite$FUNC
    );
    static final FunctionDescriptor __isnan$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __isnan$MH = RuntimeHelper.downcallHandle(
        "__isnan",
        constants$106.__isnan$FUNC
    );
    static final FunctionDescriptor __iseqsig$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __iseqsig$MH = RuntimeHelper.downcallHandle(
        "__iseqsig",
        constants$106.__iseqsig$FUNC
    );
    static final FunctionDescriptor __issignaling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __issignaling$MH = RuntimeHelper.downcallHandle(
        "__issignaling",
        constants$106.__issignaling$FUNC
    );
}


