// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$116 {

    static final FunctionDescriptor cbrt$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cbrt$MH = RuntimeHelper.downcallHandle(
        "cbrt",
        constants$116.cbrt$FUNC
    );
    static final FunctionDescriptor __cbrt$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __cbrt$MH = RuntimeHelper.downcallHandle(
        "__cbrt",
        constants$116.__cbrt$FUNC
    );
    static final FunctionDescriptor ceil$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle ceil$MH = RuntimeHelper.downcallHandle(
        "ceil",
        constants$116.ceil$FUNC
    );
    static final FunctionDescriptor __ceil$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __ceil$MH = RuntimeHelper.downcallHandle(
        "__ceil",
        constants$116.__ceil$FUNC
    );
    static final FunctionDescriptor fabs$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fabs$MH = RuntimeHelper.downcallHandle(
        "fabs",
        constants$116.fabs$FUNC
    );
    static final FunctionDescriptor __fabs$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fabs$MH = RuntimeHelper.downcallHandle(
        "__fabs",
        constants$116.__fabs$FUNC
    );
}


