// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$48 {

    static final FunctionDescriptor toascii$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle toascii$MH = RuntimeHelper.downcallHandle(
        "toascii",
        constants$48.toascii$FUNC
    );
    static final FunctionDescriptor _toupper$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _toupper$MH = RuntimeHelper.downcallHandle(
        "_toupper",
        constants$48._toupper$FUNC
    );
    static final FunctionDescriptor _tolower$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _tolower$MH = RuntimeHelper.downcallHandle(
        "_tolower",
        constants$48._tolower$FUNC
    );
    static final FunctionDescriptor isalnum_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle isalnum_l$MH = RuntimeHelper.downcallHandle(
        "isalnum_l",
        constants$48.isalnum_l$FUNC
    );
    static final FunctionDescriptor isalpha_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle isalpha_l$MH = RuntimeHelper.downcallHandle(
        "isalpha_l",
        constants$48.isalpha_l$FUNC
    );
    static final FunctionDescriptor iscntrl_l$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle iscntrl_l$MH = RuntimeHelper.downcallHandle(
        "iscntrl_l",
        constants$48.iscntrl_l$FUNC
    );
}


