// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$99 {

    static final FunctionDescriptor YR_COMPILER_INCLUDE_CALLBACK_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_COMPILER_INCLUDE_CALLBACK_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$99.YR_COMPILER_INCLUDE_CALLBACK_FUNC$FUNC
    );
    static final FunctionDescriptor YR_COMPILER_INCLUDE_FREE_FUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_COMPILER_INCLUDE_FREE_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$99.YR_COMPILER_INCLUDE_FREE_FUNC$FUNC
    );
    static final FunctionDescriptor YR_COMPILER_RE_AST_CALLBACK_FUNC$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_COMPILER_RE_AST_CALLBACK_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$99.YR_COMPILER_RE_AST_CALLBACK_FUNC$FUNC
    );
    static final FunctionDescriptor _yr_compiler_push_file_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle _yr_compiler_push_file_name$MH = RuntimeHelper.downcallHandle(
        "_yr_compiler_push_file_name",
        constants$99._yr_compiler_push_file_name$FUNC
    );
}


