// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$113 {

    static final FunctionDescriptor modf$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle modf$MH = RuntimeHelper.downcallHandle(
        "modf",
        constants$113.modf$FUNC
    );
    static final FunctionDescriptor __modf$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __modf$MH = RuntimeHelper.downcallHandle(
        "__modf",
        constants$113.__modf$FUNC
    );
    static final FunctionDescriptor expm1$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle expm1$MH = RuntimeHelper.downcallHandle(
        "expm1",
        constants$113.expm1$FUNC
    );
    static final FunctionDescriptor __expm1$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __expm1$MH = RuntimeHelper.downcallHandle(
        "__expm1",
        constants$113.__expm1$FUNC
    );
    static final FunctionDescriptor log1p$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle log1p$MH = RuntimeHelper.downcallHandle(
        "log1p",
        constants$113.log1p$FUNC
    );
    static final FunctionDescriptor __log1p$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __log1p$MH = RuntimeHelper.downcallHandle(
        "__log1p",
        constants$113.__log1p$FUNC
    );
}


