// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_ARRAY_ITEMS {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("capacity"),
        Constants$root.C_INT$LAYOUT.withName("length"),
        MemoryLayout.sequenceLayout(1, Constants$root.C_POINTER$LAYOUT).withName("objects")
    ).withName("YR_ARRAY_ITEMS");
    public static MemoryLayout $LAYOUT() {
        return YR_ARRAY_ITEMS.$struct$LAYOUT;
    }
    static final VarHandle capacity$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("capacity"));
    public static VarHandle capacity$VH() {
        return YR_ARRAY_ITEMS.capacity$VH;
    }
    public static int capacity$get(MemorySegment seg) {
        return (int)YR_ARRAY_ITEMS.capacity$VH.get(seg);
    }
    public static void capacity$set( MemorySegment seg, int x) {
        YR_ARRAY_ITEMS.capacity$VH.set(seg, x);
    }
    public static int capacity$get(MemorySegment seg, long index) {
        return (int)YR_ARRAY_ITEMS.capacity$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void capacity$set(MemorySegment seg, long index, int x) {
        YR_ARRAY_ITEMS.capacity$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("length"));
    public static VarHandle length$VH() {
        return YR_ARRAY_ITEMS.length$VH;
    }
    public static int length$get(MemorySegment seg) {
        return (int)YR_ARRAY_ITEMS.length$VH.get(seg);
    }
    public static void length$set( MemorySegment seg, int x) {
        YR_ARRAY_ITEMS.length$VH.set(seg, x);
    }
    public static int length$get(MemorySegment seg, long index) {
        return (int)YR_ARRAY_ITEMS.length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void length$set(MemorySegment seg, long index, int x) {
        YR_ARRAY_ITEMS.length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment objects$slice(MemorySegment seg) {
        return seg.asSlice(8, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


