// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_ATOMS_QUALITY_FUNC {

    int apply(java.lang.foreign.MemoryAddress config, java.lang.foreign.MemoryAddress atom);
    static MemorySegment allocate(YR_ATOMS_QUALITY_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_ATOMS_QUALITY_FUNC.class, fi, constants$95.YR_ATOMS_QUALITY_FUNC$FUNC, session);
    }
    static YR_ATOMS_QUALITY_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _config, java.lang.foreign.MemoryAddress _atom) -> {
            try {
                return (int)constants$95.YR_ATOMS_QUALITY_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_config, (java.lang.foreign.Addressable)_atom);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


