// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_HASH_TABLE_FREE_VALUE_FUNC {

    int apply(java.lang.foreign.MemoryAddress value);
    static MemorySegment allocate(YR_HASH_TABLE_FREE_VALUE_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_HASH_TABLE_FREE_VALUE_FUNC.class, fi, constants$56.YR_HASH_TABLE_FREE_VALUE_FUNC$FUNC, session);
    }
    static YR_HASH_TABLE_FREE_VALUE_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _value) -> {
            try {
                return (int)constants$57.YR_HASH_TABLE_FREE_VALUE_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_value);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


