// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_INT_ENUM_ITERATOR {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("next"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("count"),
        MemoryLayout.sequenceLayout(1, Constants$root.C_LONG_LONG$LAYOUT).withName("items")
    ).withName("YR_INT_ENUM_ITERATOR");
    public static MemoryLayout $LAYOUT() {
        return YR_INT_ENUM_ITERATOR.$struct$LAYOUT;
    }
    static final VarHandle next$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("next"));
    public static VarHandle next$VH() {
        return YR_INT_ENUM_ITERATOR.next$VH;
    }
    public static long next$get(MemorySegment seg) {
        return (long)YR_INT_ENUM_ITERATOR.next$VH.get(seg);
    }
    public static void next$set( MemorySegment seg, long x) {
        YR_INT_ENUM_ITERATOR.next$VH.set(seg, x);
    }
    public static long next$get(MemorySegment seg, long index) {
        return (long)YR_INT_ENUM_ITERATOR.next$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void next$set(MemorySegment seg, long index, long x) {
        YR_INT_ENUM_ITERATOR.next$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("count"));
    public static VarHandle count$VH() {
        return YR_INT_ENUM_ITERATOR.count$VH;
    }
    public static long count$get(MemorySegment seg) {
        return (long)YR_INT_ENUM_ITERATOR.count$VH.get(seg);
    }
    public static void count$set( MemorySegment seg, long x) {
        YR_INT_ENUM_ITERATOR.count$VH.set(seg, x);
    }
    public static long count$get(MemorySegment seg, long index) {
        return (long)YR_INT_ENUM_ITERATOR.count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, long x) {
        YR_INT_ENUM_ITERATOR.count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment items$slice(MemorySegment seg) {
        return seg.asSlice(16, 8);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


