// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$165 {

    static final FunctionDescriptor YR_EXT_DECLARATIONS_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_EXT_DECLARATIONS_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$165.YR_EXT_DECLARATIONS_FUNC$FUNC
    );
    static final FunctionDescriptor YR_EXT_LOAD_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle YR_EXT_LOAD_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$165.YR_EXT_LOAD_FUNC$FUNC
    );
    static final FunctionDescriptor YR_EXT_UNLOAD_FUNC$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle YR_EXT_UNLOAD_FUNC$MH = RuntimeHelper.downcallHandle(
        constants$165.YR_EXT_UNLOAD_FUNC$FUNC
    );
}


