// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$110 {

    static final FunctionDescriptor tanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle tanh$MH = RuntimeHelper.downcallHandle(
        "tanh",
        constants$110.tanh$FUNC
    );
    static final FunctionDescriptor __tanh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __tanh$MH = RuntimeHelper.downcallHandle(
        "__tanh",
        constants$110.__tanh$FUNC
    );
    static final FunctionDescriptor acosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle acosh$MH = RuntimeHelper.downcallHandle(
        "acosh",
        constants$110.acosh$FUNC
    );
    static final FunctionDescriptor __acosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __acosh$MH = RuntimeHelper.downcallHandle(
        "__acosh",
        constants$110.__acosh$FUNC
    );
    static final FunctionDescriptor asinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle asinh$MH = RuntimeHelper.downcallHandle(
        "asinh",
        constants$110.asinh$FUNC
    );
    static final FunctionDescriptor __asinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __asinh$MH = RuntimeHelper.downcallHandle(
        "__asinh",
        constants$110.__asinh$FUNC
    );
}


