// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$108 {

    static final FunctionDescriptor atan2$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle atan2$MH = RuntimeHelper.downcallHandle(
        "atan2",
        constants$108.atan2$FUNC
    );
    static final FunctionDescriptor __atan2$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __atan2$MH = RuntimeHelper.downcallHandle(
        "__atan2",
        constants$108.__atan2$FUNC
    );
    static final FunctionDescriptor cos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cos$MH = RuntimeHelper.downcallHandle(
        "cos",
        constants$108.cos$FUNC
    );
    static final FunctionDescriptor __cos$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __cos$MH = RuntimeHelper.downcallHandle(
        "__cos",
        constants$108.__cos$FUNC
    );
    static final FunctionDescriptor sin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sin$MH = RuntimeHelper.downcallHandle(
        "sin",
        constants$108.sin$FUNC
    );
    static final FunctionDescriptor __sin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __sin$MH = RuntimeHelper.downcallHandle(
        "__sin",
        constants$108.__sin$FUNC
    );
}


