// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$157 {

    static final FunctionDescriptor yr_scanner_print_profiling_info$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_scanner_print_profiling_info$MH = RuntimeHelper.downcallHandle(
        "yr_scanner_print_profiling_info",
        constants$157.yr_scanner_print_profiling_info$FUNC
    );
    static final FunctionDescriptor yr_rules_scan_mem_blocks$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_scan_mem_blocks$MH = RuntimeHelper.downcallHandle(
        "yr_rules_scan_mem_blocks",
        constants$157.yr_rules_scan_mem_blocks$FUNC
    );
    static final FunctionDescriptor yr_rules_scan_mem$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_scan_mem$MH = RuntimeHelper.downcallHandle(
        "yr_rules_scan_mem",
        constants$157.yr_rules_scan_mem$FUNC
    );
    static final FunctionDescriptor yr_rules_scan_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_scan_file$MH = RuntimeHelper.downcallHandle(
        "yr_rules_scan_file",
        constants$157.yr_rules_scan_file$FUNC
    );
    static final FunctionDescriptor yr_rules_scan_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_scan_fd$MH = RuntimeHelper.downcallHandle(
        "yr_rules_scan_fd",
        constants$157.yr_rules_scan_fd$FUNC
    );
    static final FunctionDescriptor yr_rules_scan_proc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_scan_proc$MH = RuntimeHelper.downcallHandle(
        "yr_rules_scan_proc",
        constants$157.yr_rules_scan_proc$FUNC
    );
}


