// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$119 {

    static final FunctionDescriptor nan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle nan$MH = RuntimeHelper.downcallHandle(
        "nan",
        constants$119.nan$FUNC
    );
    static final FunctionDescriptor __nan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __nan$MH = RuntimeHelper.downcallHandle(
        "__nan",
        constants$119.__nan$FUNC
    );
    static final FunctionDescriptor isnan$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle isnan$MH = RuntimeHelper.downcallHandle(
        "isnan",
        constants$119.isnan$FUNC
    );
    static final FunctionDescriptor j0$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle j0$MH = RuntimeHelper.downcallHandle(
        "j0",
        constants$119.j0$FUNC
    );
    static final FunctionDescriptor __j0$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __j0$MH = RuntimeHelper.downcallHandle(
        "__j0",
        constants$119.__j0$FUNC
    );
    static final FunctionDescriptor j1$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle j1$MH = RuntimeHelper.downcallHandle(
        "j1",
        constants$119.j1$FUNC
    );
}


