// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$150 {

    static final FunctionDescriptor __roundf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __roundf$MH = RuntimeHelper.downcallHandle(
        "__roundf",
        constants$150.__roundf$FUNC
    );
    static final FunctionDescriptor truncf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle truncf$MH = RuntimeHelper.downcallHandle(
        "truncf",
        constants$150.truncf$FUNC
    );
    static final FunctionDescriptor __truncf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __truncf$MH = RuntimeHelper.downcallHandle(
        "__truncf",
        constants$150.__truncf$FUNC
    );
    static final FunctionDescriptor remquof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle remquof$MH = RuntimeHelper.downcallHandle(
        "remquof",
        constants$150.remquof$FUNC
    );
    static final FunctionDescriptor __remquof$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __remquof$MH = RuntimeHelper.downcallHandle(
        "__remquof",
        constants$150.__remquof$FUNC
    );
    static final FunctionDescriptor lrintf$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle lrintf$MH = RuntimeHelper.downcallHandle(
        "lrintf",
        constants$150.lrintf$FUNC
    );
}


