// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$109 {

    static final FunctionDescriptor tan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle tan$MH = RuntimeHelper.downcallHandle(
        "tan",
        constants$109.tan$FUNC
    );
    static final FunctionDescriptor __tan$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __tan$MH = RuntimeHelper.downcallHandle(
        "__tan",
        constants$109.__tan$FUNC
    );
    static final FunctionDescriptor cosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cosh$MH = RuntimeHelper.downcallHandle(
        "cosh",
        constants$109.cosh$FUNC
    );
    static final FunctionDescriptor __cosh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __cosh$MH = RuntimeHelper.downcallHandle(
        "__cosh",
        constants$109.__cosh$FUNC
    );
    static final FunctionDescriptor sinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle sinh$MH = RuntimeHelper.downcallHandle(
        "sinh",
        constants$109.sinh$FUNC
    );
    static final FunctionDescriptor __sinh$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __sinh$MH = RuntimeHelper.downcallHandle(
        "__sinh",
        constants$109.__sinh$FUNC
    );
}


