// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$118 {

    static final FunctionDescriptor drem$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle drem$MH = RuntimeHelper.downcallHandle(
        "drem",
        constants$118.drem$FUNC
    );
    static final FunctionDescriptor __drem$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __drem$MH = RuntimeHelper.downcallHandle(
        "__drem",
        constants$118.__drem$FUNC
    );
    static final FunctionDescriptor significand$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle significand$MH = RuntimeHelper.downcallHandle(
        "significand",
        constants$118.significand$FUNC
    );
    static final FunctionDescriptor __significand$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __significand$MH = RuntimeHelper.downcallHandle(
        "__significand",
        constants$118.__significand$FUNC
    );
    static final FunctionDescriptor copysign$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle copysign$MH = RuntimeHelper.downcallHandle(
        "copysign",
        constants$118.copysign$FUNC
    );
    static final FunctionDescriptor __copysign$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __copysign$MH = RuntimeHelper.downcallHandle(
        "__copysign",
        constants$118.__copysign$FUNC
    );
}


