// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$159 {

    static final FunctionDescriptor yr_rules_define_boolean_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_rules_define_boolean_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_boolean_variable",
        constants$159.yr_rules_define_boolean_variable$FUNC
    );
    static final FunctionDescriptor yr_rules_define_float_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle yr_rules_define_float_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_float_variable",
        constants$159.yr_rules_define_float_variable$FUNC
    );
    static final FunctionDescriptor yr_rules_define_string_variable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_define_string_variable$MH = RuntimeHelper.downcallHandle(
        "yr_rules_define_string_variable",
        constants$159.yr_rules_define_string_variable$FUNC
    );
    static final FunctionDescriptor yr_rules_get_stats$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_get_stats$MH = RuntimeHelper.downcallHandle(
        "yr_rules_get_stats",
        constants$159.yr_rules_get_stats$FUNC
    );
    static final FunctionDescriptor yr_rule_disable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rule_disable$MH = RuntimeHelper.downcallHandle(
        "yr_rule_disable",
        constants$159.yr_rule_disable$FUNC
    );
    static final FunctionDescriptor yr_rule_enable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rule_enable$MH = RuntimeHelper.downcallHandle(
        "yr_rule_enable",
        constants$159.yr_rule_enable$FUNC
    );
}


