// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$126 {

    static final FunctionDescriptor __round$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __round$MH = RuntimeHelper.downcallHandle(
        "__round",
        constants$126.__round$FUNC
    );
    static final FunctionDescriptor trunc$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle trunc$MH = RuntimeHelper.downcallHandle(
        "trunc",
        constants$126.trunc$FUNC
    );
    static final FunctionDescriptor __trunc$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __trunc$MH = RuntimeHelper.downcallHandle(
        "__trunc",
        constants$126.__trunc$FUNC
    );
    static final FunctionDescriptor remquo$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle remquo$MH = RuntimeHelper.downcallHandle(
        "remquo",
        constants$126.remquo$FUNC
    );
    static final FunctionDescriptor __remquo$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __remquo$MH = RuntimeHelper.downcallHandle(
        "__remquo",
        constants$126.__remquo$FUNC
    );
    static final FunctionDescriptor lrint$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle lrint$MH = RuntimeHelper.downcallHandle(
        "lrint",
        constants$126.lrint$FUNC
    );
}


