// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$134 {

    static final FunctionDescriptor tanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle tanhf$MH = RuntimeHelper.downcallHandle(
        "tanhf",
        constants$134.tanhf$FUNC
    );
    static final FunctionDescriptor __tanhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __tanhf$MH = RuntimeHelper.downcallHandle(
        "__tanhf",
        constants$134.__tanhf$FUNC
    );
    static final FunctionDescriptor acoshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle acoshf$MH = RuntimeHelper.downcallHandle(
        "acoshf",
        constants$134.acoshf$FUNC
    );
    static final FunctionDescriptor __acoshf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __acoshf$MH = RuntimeHelper.downcallHandle(
        "__acoshf",
        constants$134.__acoshf$FUNC
    );
    static final FunctionDescriptor asinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle asinhf$MH = RuntimeHelper.downcallHandle(
        "asinhf",
        constants$134.asinhf$FUNC
    );
    static final FunctionDescriptor __asinhf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __asinhf$MH = RuntimeHelper.downcallHandle(
        "__asinhf",
        constants$134.__asinhf$FUNC
    );
}


