// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$130 {

    static final FunctionDescriptor __signbitf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __signbitf$MH = RuntimeHelper.downcallHandle(
        "__signbitf",
        constants$130.__signbitf$FUNC
    );
    static final FunctionDescriptor __isinff$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __isinff$MH = RuntimeHelper.downcallHandle(
        "__isinff",
        constants$130.__isinff$FUNC
    );
    static final FunctionDescriptor __finitef$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __finitef$MH = RuntimeHelper.downcallHandle(
        "__finitef",
        constants$130.__finitef$FUNC
    );
    static final FunctionDescriptor __isnanf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __isnanf$MH = RuntimeHelper.downcallHandle(
        "__isnanf",
        constants$130.__isnanf$FUNC
    );
    static final FunctionDescriptor __iseqsigf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __iseqsigf$MH = RuntimeHelper.downcallHandle(
        "__iseqsigf",
        constants$130.__iseqsigf$FUNC
    );
    static final FunctionDescriptor __issignalingf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __issignalingf$MH = RuntimeHelper.downcallHandle(
        "__issignalingf",
        constants$130.__issignalingf$FUNC
    );
}


