// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$132 {

    static final FunctionDescriptor atan2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle atan2f$MH = RuntimeHelper.downcallHandle(
        "atan2f",
        constants$132.atan2f$FUNC
    );
    static final FunctionDescriptor __atan2f$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __atan2f$MH = RuntimeHelper.downcallHandle(
        "__atan2f",
        constants$132.__atan2f$FUNC
    );
    static final FunctionDescriptor cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle cosf$MH = RuntimeHelper.downcallHandle(
        "cosf",
        constants$132.cosf$FUNC
    );
    static final FunctionDescriptor __cosf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __cosf$MH = RuntimeHelper.downcallHandle(
        "__cosf",
        constants$132.__cosf$FUNC
    );
    static final FunctionDescriptor sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle sinf$MH = RuntimeHelper.downcallHandle(
        "sinf",
        constants$132.sinf$FUNC
    );
    static final FunctionDescriptor __sinf$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __sinf$MH = RuntimeHelper.downcallHandle(
        "__sinf",
        constants$132.__sinf$FUNC
    );
}


