// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$160 {

    static final FunctionDescriptor yr_rules_from_arena$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_rules_from_arena$MH = RuntimeHelper.downcallHandle(
        "yr_rules_from_arena",
        constants$160.yr_rules_from_arena$FUNC
    );
    static final FunctionDescriptor yr_scan_verify_match$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle yr_scan_verify_match$MH = RuntimeHelper.downcallHandle(
        "yr_scan_verify_match",
        constants$160.yr_scan_verify_match$FUNC
    );
    static final FunctionDescriptor yr_execute_code$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_execute_code$MH = RuntimeHelper.downcallHandle(
        "yr_execute_code",
        constants$160.yr_execute_code$FUNC
    );
    static final FunctionDescriptor yr_object_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_create$MH = RuntimeHelper.downcallHandle(
        "yr_object_create",
        constants$160.yr_object_create$FUNC
    );
    static final FunctionDescriptor yr_object_set_canary$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_object_set_canary$MH = RuntimeHelper.downcallHandle(
        "yr_object_set_canary",
        constants$160.yr_object_set_canary$FUNC
    );
    static final FunctionDescriptor yr_object_function_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_function_create$MH = RuntimeHelper.downcallHandle(
        "yr_object_function_create",
        constants$160.yr_object_function_create$FUNC
    );
}


