// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$163 {

    static final FunctionDescriptor yr_object_array_length$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_array_length$MH = RuntimeHelper.downcallHandle(
        "yr_object_array_length",
        constants$163.yr_object_array_length$FUNC
    );
    static final FunctionDescriptor yr_object_array_get_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_object_array_get_item$MH = RuntimeHelper.downcallHandle(
        "yr_object_array_get_item",
        constants$163.yr_object_array_get_item$FUNC
    );
    static final FunctionDescriptor yr_object_array_set_item$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle yr_object_array_set_item$MH = RuntimeHelper.downcallHandle(
        "yr_object_array_set_item",
        constants$163.yr_object_array_set_item$FUNC
    );
    static final FunctionDescriptor yr_object_dict_get_item$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_dict_get_item$MH = RuntimeHelper.downcallHandle(
        "yr_object_dict_get_item",
        constants$163.yr_object_dict_get_item$FUNC
    );
    static final FunctionDescriptor yr_object_dict_set_item$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_dict_set_item$MH = RuntimeHelper.downcallHandle(
        "yr_object_dict_set_item",
        constants$163.yr_object_dict_set_item$FUNC
    );
    static final FunctionDescriptor yr_object_structure_set_member$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle yr_object_structure_set_member$MH = RuntimeHelper.downcallHandle(
        "yr_object_structure_set_member",
        constants$163.yr_object_structure_set_member$FUNC
    );
}


