// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$124 {

    static final FunctionDescriptor __nextafter$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __nextafter$MH = RuntimeHelper.downcallHandle(
        "__nextafter",
        constants$124.__nextafter$FUNC
    );
    static final FunctionDescriptor remainder$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle remainder$MH = RuntimeHelper.downcallHandle(
        "remainder",
        constants$124.remainder$FUNC
    );
    static final FunctionDescriptor __remainder$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __remainder$MH = RuntimeHelper.downcallHandle(
        "__remainder",
        constants$124.__remainder$FUNC
    );
    static final FunctionDescriptor scalbn$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle scalbn$MH = RuntimeHelper.downcallHandle(
        "scalbn",
        constants$124.scalbn$FUNC
    );
    static final FunctionDescriptor __scalbn$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle __scalbn$MH = RuntimeHelper.downcallHandle(
        "__scalbn",
        constants$124.__scalbn$FUNC
    );
    static final FunctionDescriptor ilogb$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle ilogb$MH = RuntimeHelper.downcallHandle(
        "ilogb",
        constants$124.ilogb$FUNC
    );
}


