// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$128 {

    static final FunctionDescriptor __llround$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __llround$MH = RuntimeHelper.downcallHandle(
        "__llround",
        constants$128.__llround$FUNC
    );
    static final FunctionDescriptor fdim$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fdim$MH = RuntimeHelper.downcallHandle(
        "fdim",
        constants$128.fdim$FUNC
    );
    static final FunctionDescriptor __fdim$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fdim$MH = RuntimeHelper.downcallHandle(
        "__fdim",
        constants$128.__fdim$FUNC
    );
    static final FunctionDescriptor fmax$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fmax$MH = RuntimeHelper.downcallHandle(
        "fmax",
        constants$128.fmax$FUNC
    );
    static final FunctionDescriptor __fmax$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fmax$MH = RuntimeHelper.downcallHandle(
        "__fmax",
        constants$128.__fmax$FUNC
    );
    static final FunctionDescriptor fmin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fmin$MH = RuntimeHelper.downcallHandle(
        "fmin",
        constants$128.fmin$FUNC
    );
}


