// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$129 {

    static final FunctionDescriptor __fmin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fmin$MH = RuntimeHelper.downcallHandle(
        "__fmin",
        constants$129.__fmin$FUNC
    );
    static final FunctionDescriptor fma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle fma$MH = RuntimeHelper.downcallHandle(
        "fma",
        constants$129.fma$FUNC
    );
    static final FunctionDescriptor __fma$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __fma$MH = RuntimeHelper.downcallHandle(
        "__fma",
        constants$129.__fma$FUNC
    );
    static final FunctionDescriptor scalb$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle scalb$MH = RuntimeHelper.downcallHandle(
        "scalb",
        constants$129.scalb$FUNC
    );
    static final FunctionDescriptor __scalb$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle __scalb$MH = RuntimeHelper.downcallHandle(
        "__scalb",
        constants$129.__scalb$FUNC
    );
    static final FunctionDescriptor __fpclassifyf$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle __fpclassifyf$MH = RuntimeHelper.downcallHandle(
        "__fpclassifyf",
        constants$129.__fpclassifyf$FUNC
    );
}


