// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_ARENA_BUFFER {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("size"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("used")
    ).withName("YR_ARENA_BUFFER");
    public static MemoryLayout $LAYOUT() {
        return YR_ARENA_BUFFER.$struct$LAYOUT;
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return YR_ARENA_BUFFER.data$VH;
    }
    public static MemoryAddress data$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_ARENA_BUFFER.data$VH.get(seg);
    }
    public static void data$set( MemorySegment seg, MemoryAddress x) {
        YR_ARENA_BUFFER.data$VH.set(seg, x);
    }
    public static MemoryAddress data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_ARENA_BUFFER.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_ARENA_BUFFER.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("size"));
    public static VarHandle size$VH() {
        return YR_ARENA_BUFFER.size$VH;
    }
    public static long size$get(MemorySegment seg) {
        return (long)YR_ARENA_BUFFER.size$VH.get(seg);
    }
    public static void size$set( MemorySegment seg, long x) {
        YR_ARENA_BUFFER.size$VH.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)YR_ARENA_BUFFER.size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        YR_ARENA_BUFFER.size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle used$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("used"));
    public static VarHandle used$VH() {
        return YR_ARENA_BUFFER.used$VH;
    }
    public static long used$get(MemorySegment seg) {
        return (long)YR_ARENA_BUFFER.used$VH.get(seg);
    }
    public static void used$set( MemorySegment seg, long x) {
        YR_ARENA_BUFFER.used$VH.set(seg, x);
    }
    public static long used$get(MemorySegment seg, long index) {
        return (long)YR_ARENA_BUFFER.used$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void used$set(MemorySegment seg, long index, long x) {
        YR_ARENA_BUFFER.used$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


