// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_ATOM_TREE {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("root_node")
    ).withName("YR_ATOM_TREE");
    public static MemoryLayout $LAYOUT() {
        return YR_ATOM_TREE.$struct$LAYOUT;
    }
    static final VarHandle root_node$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("root_node"));
    public static VarHandle root_node$VH() {
        return YR_ATOM_TREE.root_node$VH;
    }
    public static MemoryAddress root_node$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_ATOM_TREE.root_node$VH.get(seg);
    }
    public static void root_node$set( MemorySegment seg, MemoryAddress x) {
        YR_ATOM_TREE.root_node$VH.set(seg, x);
    }
    public static MemoryAddress root_node$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_ATOM_TREE.root_node$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void root_node$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_ATOM_TREE.root_node$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


