// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_COMPILER_INCLUDE_FREE_FUNC {

    void apply(java.lang.foreign.MemoryAddress callback_result_ptr, java.lang.foreign.MemoryAddress user_data);
    static MemorySegment allocate(YR_COMPILER_INCLUDE_FREE_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_COMPILER_INCLUDE_FREE_FUNC.class, fi, constants$99.YR_COMPILER_INCLUDE_FREE_FUNC$FUNC, session);
    }
    static YR_COMPILER_INCLUDE_FREE_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _callback_result_ptr, java.lang.foreign.MemoryAddress _user_data) -> {
            try {
                constants$99.YR_COMPILER_INCLUDE_FREE_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_callback_result_ptr, (java.lang.foreign.Addressable)_user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


