// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_COMPILER_INCLUDE_CALLBACK_FUNC {

    java.lang.foreign.Addressable apply(java.lang.foreign.MemoryAddress include_name, java.lang.foreign.MemoryAddress calling_rule_filename, java.lang.foreign.MemoryAddress calling_rule_namespace, java.lang.foreign.MemoryAddress user_data);
    static MemorySegment allocate(YR_COMPILER_INCLUDE_CALLBACK_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_COMPILER_INCLUDE_CALLBACK_FUNC.class, fi, constants$98.YR_COMPILER_INCLUDE_CALLBACK_FUNC$FUNC, session);
    }
    static YR_COMPILER_INCLUDE_CALLBACK_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _include_name, java.lang.foreign.MemoryAddress _calling_rule_filename, java.lang.foreign.MemoryAddress _calling_rule_namespace, java.lang.foreign.MemoryAddress _user_data) -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$99.YR_COMPILER_INCLUDE_CALLBACK_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_include_name, (java.lang.foreign.Addressable)_calling_rule_filename, (java.lang.foreign.Addressable)_calling_rule_namespace, (java.lang.foreign.Addressable)_user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


