// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_EXT_LOAD_FUNC {

    int apply(java.lang.foreign.MemoryAddress context, java.lang.foreign.MemoryAddress module_object, java.lang.foreign.MemoryAddress module_data, long module_data_size);
    static MemorySegment allocate(YR_EXT_LOAD_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_EXT_LOAD_FUNC.class, fi, constants$165.YR_EXT_LOAD_FUNC$FUNC, session);
    }
    static YR_EXT_LOAD_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _context, java.lang.foreign.MemoryAddress _module_object, java.lang.foreign.MemoryAddress _module_data, long _module_data_size) -> {
            try {
                return (int)constants$165.YR_EXT_LOAD_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_context, (java.lang.foreign.Addressable)_module_object, (java.lang.foreign.Addressable)_module_data, _module_data_size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


