// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_ITERATOR_NEXT_FUNC {

    int apply(java.lang.foreign.MemoryAddress self, java.lang.foreign.MemoryAddress stack);
    static MemorySegment allocate(YR_ITERATOR_NEXT_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_ITERATOR_NEXT_FUNC.class, fi, constants$91.YR_ITERATOR_NEXT_FUNC$FUNC, session);
    }
    static YR_ITERATOR_NEXT_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _self, java.lang.foreign.MemoryAddress _stack) -> {
            try {
                return (int)constants$92.YR_ITERATOR_NEXT_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_self, (java.lang.foreign.Addressable)_stack);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


