// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC {

    long apply(java.lang.foreign.MemoryAddress self);
    static MemorySegment allocate(YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC.class, fi, constants$90.YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC$FUNC, session);
    }
    static YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _self) -> {
            try {
                return (long)constants$91.YR_MEMORY_BLOCK_ITERATOR_SIZE_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_self);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


