// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_MODULE_FUNC {

    int apply(java.lang.foreign.MemoryAddress args, java.lang.foreign.MemoryAddress context, java.lang.foreign.MemoryAddress function_obj);
    static MemorySegment allocate(YR_MODULE_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_MODULE_FUNC.class, fi, constants$91.YR_MODULE_FUNC$FUNC, session);
    }
    static YR_MODULE_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _args, java.lang.foreign.MemoryAddress _context, java.lang.foreign.MemoryAddress _function_obj) -> {
            try {
                return (int)constants$91.YR_MODULE_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_args, (java.lang.foreign.Addressable)_context, (java.lang.foreign.Addressable)_function_obj);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


