// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_MATCHES {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("head"),
        Constants$root.C_POINTER$LAYOUT.withName("tail"),
        Constants$root.C_INT$LAYOUT.withName("count"),
        MemoryLayout.paddingLayout(32)
    ).withName("YR_MATCHES");
    public static MemoryLayout $LAYOUT() {
        return YR_MATCHES.$struct$LAYOUT;
    }
    static final VarHandle head$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("head"));
    public static VarHandle head$VH() {
        return YR_MATCHES.head$VH;
    }
    public static MemoryAddress head$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_MATCHES.head$VH.get(seg);
    }
    public static void head$set( MemorySegment seg, MemoryAddress x) {
        YR_MATCHES.head$VH.set(seg, x);
    }
    public static MemoryAddress head$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_MATCHES.head$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void head$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_MATCHES.head$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle tail$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tail"));
    public static VarHandle tail$VH() {
        return YR_MATCHES.tail$VH;
    }
    public static MemoryAddress tail$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_MATCHES.tail$VH.get(seg);
    }
    public static void tail$set( MemorySegment seg, MemoryAddress x) {
        YR_MATCHES.tail$VH.set(seg, x);
    }
    public static MemoryAddress tail$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_MATCHES.tail$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tail$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_MATCHES.tail$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("count"));
    public static VarHandle count$VH() {
        return YR_MATCHES.count$VH;
    }
    public static int count$get(MemorySegment seg) {
        return (int)YR_MATCHES.count$VH.get(seg);
    }
    public static void count$set( MemorySegment seg, int x) {
        YR_MATCHES.count$VH.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)YR_MATCHES.count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        YR_MATCHES.count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


