// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_OBJECT_FUNCTION {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("canary"),
        Constants$root.C_CHAR$LAYOUT.withName("type"),
        MemoryLayout.paddingLayout(24),
        Constants$root.C_POINTER$LAYOUT.withName("identifier"),
        Constants$root.C_POINTER$LAYOUT.withName("parent"),
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_POINTER$LAYOUT.withName("return_obj"),
        MemoryLayout.sequenceLayout(10, MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("arguments_fmt"),
            Constants$root.C_POINTER$LAYOUT.withName("code")
        )).withName("prototypes")
    ).withName("YR_OBJECT_FUNCTION");
    public static MemoryLayout $LAYOUT() {
        return YR_OBJECT_FUNCTION.$struct$LAYOUT;
    }
    static final VarHandle canary$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("canary"));
    public static VarHandle canary$VH() {
        return YR_OBJECT_FUNCTION.canary$VH;
    }
    public static int canary$get(MemorySegment seg) {
        return (int)YR_OBJECT_FUNCTION.canary$VH.get(seg);
    }
    public static void canary$set( MemorySegment seg, int x) {
        YR_OBJECT_FUNCTION.canary$VH.set(seg, x);
    }
    public static int canary$get(MemorySegment seg, long index) {
        return (int)YR_OBJECT_FUNCTION.canary$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void canary$set(MemorySegment seg, long index, int x) {
        YR_OBJECT_FUNCTION.canary$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return YR_OBJECT_FUNCTION.type$VH;
    }
    public static byte type$get(MemorySegment seg) {
        return (byte)YR_OBJECT_FUNCTION.type$VH.get(seg);
    }
    public static void type$set( MemorySegment seg, byte x) {
        YR_OBJECT_FUNCTION.type$VH.set(seg, x);
    }
    public static byte type$get(MemorySegment seg, long index) {
        return (byte)YR_OBJECT_FUNCTION.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, byte x) {
        YR_OBJECT_FUNCTION.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle identifier$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("identifier"));
    public static VarHandle identifier$VH() {
        return YR_OBJECT_FUNCTION.identifier$VH;
    }
    public static MemoryAddress identifier$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.identifier$VH.get(seg);
    }
    public static void identifier$set( MemorySegment seg, MemoryAddress x) {
        YR_OBJECT_FUNCTION.identifier$VH.set(seg, x);
    }
    public static MemoryAddress identifier$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.identifier$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void identifier$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_OBJECT_FUNCTION.identifier$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle parent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("parent"));
    public static VarHandle parent$VH() {
        return YR_OBJECT_FUNCTION.parent$VH;
    }
    public static MemoryAddress parent$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.parent$VH.get(seg);
    }
    public static void parent$set( MemorySegment seg, MemoryAddress x) {
        YR_OBJECT_FUNCTION.parent$VH.set(seg, x);
    }
    public static MemoryAddress parent$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.parent$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void parent$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_OBJECT_FUNCTION.parent$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return YR_OBJECT_FUNCTION.data$VH;
    }
    public static MemoryAddress data$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.data$VH.get(seg);
    }
    public static void data$set( MemorySegment seg, MemoryAddress x) {
        YR_OBJECT_FUNCTION.data$VH.set(seg, x);
    }
    public static MemoryAddress data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_OBJECT_FUNCTION.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle return_obj$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("return_obj"));
    public static VarHandle return_obj$VH() {
        return YR_OBJECT_FUNCTION.return_obj$VH;
    }
    public static MemoryAddress return_obj$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.return_obj$VH.get(seg);
    }
    public static void return_obj$set( MemorySegment seg, MemoryAddress x) {
        YR_OBJECT_FUNCTION.return_obj$VH.set(seg, x);
    }
    public static MemoryAddress return_obj$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_OBJECT_FUNCTION.return_obj$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void return_obj$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_OBJECT_FUNCTION.return_obj$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment prototypes$slice(MemorySegment seg) {
        return seg.asSlice(40, 160);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


