// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface YR_STREAM_READ_FUNC {

    long apply(java.lang.foreign.MemoryAddress ptr, long size, long count, java.lang.foreign.MemoryAddress user_data);
    static MemorySegment allocate(YR_STREAM_READ_FUNC fi, MemorySession session) {
        return RuntimeHelper.upcallStub(YR_STREAM_READ_FUNC.class, fi, constants$51.YR_STREAM_READ_FUNC$FUNC, session);
    }
    static YR_STREAM_READ_FUNC ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _ptr, long _size, long _count, java.lang.foreign.MemoryAddress _user_data) -> {
            try {
                return (long)constants$51.YR_STREAM_READ_FUNC$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_ptr, _size, _count, (java.lang.foreign.Addressable)_user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


