// Generated by jextract

package com.virustotal.yara;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class YR_VALUE_STACK {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sp"),
        Constants$root.C_INT$LAYOUT.withName("capacity"),
        Constants$root.C_POINTER$LAYOUT.withName("items")
    ).withName("YR_VALUE_STACK");
    public static MemoryLayout $LAYOUT() {
        return YR_VALUE_STACK.$struct$LAYOUT;
    }
    static final VarHandle sp$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("sp"));
    public static VarHandle sp$VH() {
        return YR_VALUE_STACK.sp$VH;
    }
    public static int sp$get(MemorySegment seg) {
        return (int)YR_VALUE_STACK.sp$VH.get(seg);
    }
    public static void sp$set( MemorySegment seg, int x) {
        YR_VALUE_STACK.sp$VH.set(seg, x);
    }
    public static int sp$get(MemorySegment seg, long index) {
        return (int)YR_VALUE_STACK.sp$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sp$set(MemorySegment seg, long index, int x) {
        YR_VALUE_STACK.sp$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle capacity$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("capacity"));
    public static VarHandle capacity$VH() {
        return YR_VALUE_STACK.capacity$VH;
    }
    public static int capacity$get(MemorySegment seg) {
        return (int)YR_VALUE_STACK.capacity$VH.get(seg);
    }
    public static void capacity$set( MemorySegment seg, int x) {
        YR_VALUE_STACK.capacity$VH.set(seg, x);
    }
    public static int capacity$get(MemorySegment seg, long index) {
        return (int)YR_VALUE_STACK.capacity$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void capacity$set(MemorySegment seg, long index, int x) {
        YR_VALUE_STACK.capacity$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle items$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("items"));
    public static VarHandle items$VH() {
        return YR_VALUE_STACK.items$VH;
    }
    public static MemoryAddress items$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)YR_VALUE_STACK.items$VH.get(seg);
    }
    public static void items$set( MemorySegment seg, MemoryAddress x) {
        YR_VALUE_STACK.items$VH.set(seg, x);
    }
    public static MemoryAddress items$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)YR_VALUE_STACK.items$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void items$set(MemorySegment seg, long index, MemoryAddress x) {
        YR_VALUE_STACK.items$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


